### ISSUE TITLE
XLS Exporter Issue

### ISSUE THREAD

**Issue by TQ-MandarMehta** [dynamicreports/dynamicreports#199]
Hi Team,

Currently facing the below issue : 
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/poi/ss/usermodel/Sheet
	at net.sf.dynamicreports.jasper.transformation.ExporterTransform.xls(ExporterTransform.java:772)
	at net.sf.dynamicreports.jasper.transformation.ExporterTransform.transform(ExporterTransform.java:136)
	at net.sf.dynamicreports.jasper.builder.JasperReportBuilder.export(JasperReportBuilder.java:914)
	at net.sf.dynamicreports.jasper.builder.JasperReportBuilder.toXls(JasperReportBuilder.java:825)
	at com.kmbl.gbs.reporting.util.ReportGenerator.generatePlainExcel(ReportGenerator.java:93)
	at com.kmbl.gbs.reporting.util.SampleMain.main(SampleMain.java:116)
Caused by: java.lang.ClassNotFoundException: org.apache.poi.ss.usermodel.Sheet
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
	... 6 more

For the following code snippet : 
JRDataSource dataSource = createDataSource();
JasperReportBuilder report = DynamicReports.report();
report.setDataSource(dataSource).toXls(DynamicReports.export.xlsExporter("AAAA.xls"));

I am able to generate the xlsx pdf but issue only with the xls.

the POM Dependencies as follows I have excluded and added latest versions of some internal dependencies as it fails OWASP check and also causes Dependency Convergence

<dependencies>
        
        
        <dependency>
            <groupId>net.sourceforge.dynamicreports</groupId>
            <artifactId>dynamicreports-core</artifactId>
            <version>6.20.1</version>
            <exclusions>
                <exclusion>
                    <groupId>org.jfree</groupId>
                    <artifactId>jfreechart</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>commons-io</groupId>
                    <artifactId>commons-io</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>org.apache.ant</groupId>
                    <artifactId>ant</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>org.apache.ant</groupId>
                    <artifactId>ant-launcher</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>commons-logging</groupId>
                    <artifactId>commons-logging</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>commons-beanutils</groupId>
                    <artifactId>commons-beanutils</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>com.fasterxml.jackson.core</groupId>
                    <artifactId>jackson-databind</artifactId>
                </exclusion>
            </exclusions>
        </dependency>

        
        <dependency>
            <groupId>org.jfree</groupId>
            <artifactId>jfreechart</artifactId>
            <version>1.5.5</version>
        </dependency>

        
        <dependency>
            <groupId>commons-io</groupId>
            <artifactId>commons-io</artifactId>
            <version>2.18.0</version>
        </dependency>

        
        <dependency>
            <groupId>org.apache.ant</groupId>
            <artifactId>ant</artifactId>
            <version>1.10.15</version>
        </dependency>

        
        <dependency>
            <groupId>org.apache.ant</groupId>
            <artifactId>ant-launcher</artifactId>
            <version>1.10.15</version>
        </dependency>

        
        <dependency>
            <groupId>commons-logging</groupId>
            <artifactId>commons-logging</artifactId>
            <version>1.1.1</version>
        </dependency>

        
        <dependency>
            <groupId>commons-beanutils</groupId>
            <artifactId>commons-beanutils</artifactId>
            <version>1.9.4</version>
            <exclusions>
                <exclusion>
                    <groupId>commons-logging</groupId>
                    <artifactId>commons-logging</artifactId>
                </exclusion>
            </exclusions>
        </dependency>

        
        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-databind</artifactId>
            <version>2.18.2</version>
        </dependency>

        
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <version>1.18.36</version>
            <scope>provided</scope>
        </dependency>

    </dependencies>

Kindly help on priority as it is causing delay for one of deliverables.

Thanks in advance!!

**Comment by Okiring** [comment]
i think your missing the poi library. Try adding the below to your pom file:

      <dependency>
            <groupId>org.apache.poi</groupId>
            <artifactId>poi</artifactId>
	   <version>3.15</version>
        </dependency>

**Comment by TQ-MandarMehta** [comment]
Receiving a different error after addition of  above mentioned POI dependency : 

Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/poi/hssf/util/HSSFColor$HSSFColorPredefined
	at net.sf.jasperreports.engine.export.JRXlsExporter.<init>(JRXlsExporter.java:195)
	at net.sf.jasperreports.engine.export.JRXlsExporter.<init>(JRXlsExporter.java:217)
	at net.sf.dynamicreports.jasper.transformation.ExporterTransform.xls(ExporterTransform.java:772)
	at net.sf.dynamicreports.jasper.transformation.ExporterTransform.transform(ExporterTransform.java:136)
	at net.sf.dynamicreports.jasper.builder.JasperReportBuilder.export(JasperReportBuilder.java:914)
	at net.sf.dynamicreports.jasper.builder.JasperReportBuilder.toXls(JasperReportBuilder.java:825)
	at com.kmbl.gbs.reporting.util.ReportGenerator.generatePlainExcel(ReportGenerator.java:97)
	at com.kmbl.gbs.reporting.util.SampleMain.main(SampleMain.java:116)
Caused by: java.lang.ClassNotFoundException: org.apache.poi.hssf.util.HSSFColor$HSSFColorPredefined
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
	... 8 more

**Comment by TQ-MandarMehta** [comment]
> i think your missing the poi library. Try adding the below to your pom file:
> 
> ```
>   <dependency>
>         <groupId>org.apache.poi</groupId>
>         <artifactId>poi</artifactId>
>    <version>3.15</version>
>     </dependency>
> ```

Receiving a different error after addition of above mentioned POI dependency :

Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/poi/hssf/util/HSSFColor$HSSFColorPredefined
at net.sf.jasperreports.engine.export.JRXlsExporter.(JRXlsExporter.java:195)
at net.sf.jasperreports.engine.export.JRXlsExporter.(JRXlsExporter.java:217)
at net.sf.dynamicreports.jasper.transformation.ExporterTransform.xls(ExporterTransform.java:772)
at net.sf.dynamicreports.jasper.transformation.ExporterTransform.transform(ExporterTransform.java:136)
at net.sf.dynamicreports.jasper.builder.JasperReportBuilder.export(JasperReportBuilder.java:914)
at net.sf.dynamicreports.jasper.builder.JasperReportBuilder.toXls(JasperReportBuilder.java:825)
at com.kmbl.gbs.reporting.util.ReportGenerator.generatePlainExcel(ReportGenerator.java:97)
at com.kmbl.gbs.reporting.util.SampleMain.main(SampleMain.java:116)
Caused by: java.lang.ClassNotFoundException: org.apache.poi.hssf.util.HSSFColor$HSSFColorPredefined
at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
... 8 more

**Comment by TQ-MandarMehta** [comment]
Hi @Okiring,

The issue got resolved by using latest POI

<dependency>
        <groupId>org.apache.poi</groupId>
        <artifactId>poi</artifactId>
   <version>5.3.0</version>
 </dependency> 

But for some reason when I used it earlier it still threw an error but today it worked. Kindly find the below the Final dependencies
Note :- I am running OWASP for vulnerabilities scan so multiple excluded and latest used. 0 vulnerabilities for below. Hope the team can update vulnerable dependencies in next release. 

`

<dependencies>
        
        
        <dependency>
            <groupId>net.sourceforge.dynamicreports</groupId>
            <artifactId>dynamicreports-core</artifactId>
            <version>6.20.1</version>
            <exclusions>
                <exclusion>
                    <groupId>org.jfree</groupId>
                    <artifactId>jfreechart</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>commons-io</groupId>
                    <artifactId>commons-io</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>org.apache.ant</groupId>
                    <artifactId>ant</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>org.apache.ant</groupId>
                    <artifactId>ant-launcher</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>commons-logging</groupId>
                    <artifactId>commons-logging</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>commons-beanutils</groupId>
                    <artifactId>commons-beanutils</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>com.fasterxml.jackson.core</groupId>
                    <artifactId>jackson-databind</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>org.apache.commons</groupId>
                    <artifactId>commons-collections4</artifactId>
                </exclusion>
            </exclusions>
        </dependency>

        
        <dependency>
            <groupId>org.jfree</groupId>
            <artifactId>jfreechart</artifactId>
            <version>1.5.5</version>
        </dependency>

        
        <dependency>
            <groupId>commons-io</groupId>
            <artifactId>commons-io</artifactId>
            <version>2.18.0</version>
        </dependency>

        
        <dependency>
            <groupId>org.apache.ant</groupId>
            <artifactId>ant</artifactId>
            <version>1.10.15</version>
        </dependency>

        
        <dependency>
            <groupId>org.apache.ant</groupId>
            <artifactId>ant-launcher</artifactId>
            <version>1.10.15</version>
        </dependency>

        
        <dependency>
            <groupId>commons-logging</groupId>
            <artifactId>commons-logging</artifactId>
            <version>1.3.4</version>
        </dependency>

        
        <dependency>
            <groupId>commons-beanutils</groupId>
            <artifactId>commons-beanutils</artifactId>
            <version>1.9.4</version>
            <exclusions>
                <exclusion>
                    <groupId>commons-logging</groupId>
                    <artifactId>commons-logging</artifactId>
                </exclusion>
            </exclusions>
        </dependency>

        
        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-databind</artifactId>
            <version>2.18.2</version>
        </dependency>

        
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <version>1.18.36</version>
            <scope>provided</scope>
        </dependency>

         
        <dependency>
            <groupId>org.apache.poi</groupId>
            <artifactId>poi</artifactId>
            <version>5.3.0</version>
            <exclusions>
                <exclusion>
                    <groupId>commons-io</groupId>
                    <artifactId>commons-io</artifactId>
                </exclusion>
            </exclusions>
        </dependency>

    </dependencies>
`

Thanks for the support!
